apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  labels:
    app: api-service
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: "unicornmarlin12/api-service"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: INFLUXDB_URL
              value: "http://influxdb2.monitoring.svc.cluster.local:80"
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb2-auth
                  key: admin-token
            - name: INFLUXDB_ORG
              value: "influxdata"
            - name: INFLUXDB_BUCKET
              value: "bucket"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: monitoring
spec:
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
